### ISSUE TITLE
無視できないレベルのバグ発生。

### ISSUE THREAD

**Issue by sirosuzu** [ArtemisJPN/RPG_MZ_PROJECT#2]
前に修正してもらいましたARTM_PlayerSensorMZにて、無視できないレベルのバグが発生しています。
イベント内の出現条件にてセルフスイッチ以外の条件を付属させるとそのページの機能が正常に動かなくなります。
修正前までは発生していなかったもので、正直前のバグより被害が甚大ゆえにグレードダウンをしていただきたいレベルで無視できない状態になってしまっています。
もし可能なら以前の、ひとつ前のバージョンのファイル等をいただけないでしょうか？

**Comment by ArtemisJPN** [comment]
少々お待ちください。
今から1.10 に戻します。

**Comment by sirosuzu** [comment]
ありがとうございます。
別の方がMZ版に移植していた大分前のやつも似たようなバグが発生していたことが確認できていたので、恐らくMV盤から移植したときに共通して何かしらエラーを履いてる部分があるのだと思います。

**Comment by ArtemisJPN** [comment]
最新版をご取得下さい。
（以前ご報告のあった遅延ゼロ時の扇探索不具合（本家MV版でも発生している）対策は完了したのですが、デグレの発生率が高いため、こちらの最新版への反映は中止致します。ご了承下さい。）

**Comment by sirosuzu** [comment]
すみません！DLしたのですが
Unexpected token '<'となって読み込みもできなくなってしまいました…。
何か抜けているのかもしれません。

**Comment by sirosuzu** [comment]
すみません…！再度DLしたら治りました。タイムラグでファイルが正常でなかっただけみたいです。

**Comment by sirosuzu** [comment]
一先ず確認したところ、一部は復旧できました。
ですがやはり以前のVerまでは出来ていた全ページ出現条件が決まっているイベント。最初は消えてるイベント系は前まではスイッチがONになった瞬間、出現と同時に探索が始まっていましたがこのVerでもそれはできない感じでした。
一応これぐらいなら何もないページを最初に差し込んでおくだけで動くので、ここは妥協しようと思います。
対応ありがとうございました。

**Comment by ArtemisJPN** [comment]
sirosuzuさん、DLできたようでよかったです。
昨日報告いただいた扇探索座標の不具合ですが、実はMKR_PlayerSensor3.1.1でも発生していました。（動作確認済み）
MZ版での対応策は暫定で完成したのですが、MZ特有の不具合が誘発される危険性大のため、ひとまずこの不具合は中断とさせて頂きます。
せっかくご報告いただいたのに申し訳ありません。

**Comment by ArtemisJPN** [comment]
sirosuzuさん、下記からv1.0.0をダウンロードできます。
不具合を一切対応していない、ベースバージョンですので動作保証はありませんが。。
https://106.gigafile.nu/0104-b0c44a6f3a80a0173d3767bbc5f62c98b

**Comment by ArtemisJPN** [comment]
> ですがやはり以前のVerまでは出来ていた全ページ出現条件が決まっているイベント。最初は消えてるイベント系は前まではスイッチがONになった瞬間、出現と同時に探索が始まっていましたがこのVerでもそれはできない感じでした。

上記は、本プラグインのver1.0.0で確認したところ同様の現象が発生しました。
**RPGツクールMZのバージョンが上がった際に挙動が変わってしまったものかと思います。**
実際に、直線探索もRPGツクールMZのバージョンが上がったことで挙動がおかしくなりました。(ARTM_PlayerSensorMZ1.0.3で対応済）
